ROOT = "VideoCameraManager/stream/"
LOG_DIR = ROOT+"logs/"
MODEL_DIR = ROOT+"model/"
VIDEO_TAPES_DIR = LOG_DIR+"videos/"

INPUT_MEAN = 127.5
INPUT_STD = 127.5
MIN_CONF_THRESHOLD = 0.5

RECORDING_FRAME_COUNT = 5
